################# RCInstance Config #################
configversion: 1  # Do not touch this!
#####################################################
################# Main Configuration ################
#####################################################
mainWorld: world
#####################################################
############### Instance Configuration ##############
#####################################################
instances:
    Instance1:
        world: world1
        players: 5
        timer: 3600
        exp: 40